### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by MahirAbbas** [robotman2412/nebula-risc-v#9]
- [ ]  Basic frontend
- [x]  Decoder
- [x]  Integer ALU / Shift
- [ ]  Get I/R-type instr working
- [ ]  Basic testbench
- [ ]  Writeback
- [ ]  Branch
- [ ]  Floating point
- [ ]  Load / Store
- [ ]  Basic CSR support
- [x]  mul / div / rem
- [ ]  Passing riscv-test
- [ ]  BTB + RAS predictor
- [ ]  Passing riscv-arch-test (RISC-V Architectural Self Checking Tests)
- [ ]  Passing embench / coremark / dhrystone in dual issue
- [ ]  Exception support
- [ ]  Interrupt support
- [ ]  RV32 + RV64 support
- [ ]  Privilege / CSR implemented
- [ ]  Run FreeRTOS tests
- [ ]  MMU
- [ ]  RVA
- [ ]  Linux / buildroot / opensbi
- [ ]  Multi issue fetch's aligner
- [ ]  RVC
- [ ]  I$ 
- [ ]  D$ 
- [ ]  Cache Coherency 
- [ ]  SoC
- [ ]  PMP
- [ ]  GShare predictor
- [ ] Multi-Issue
- [ ]  RVLS integration
- [ ]  Konata traces
- [ ]  Regression framework
